/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BangGiaRouteImport } from './routes/bang-gia'
import { Route as BaoTriDienLanhRouteImport } from './routes/bao-tri-dien-lanh'
import { Route as CauHoiThuongGapRouteImport } from './routes/cau-hoi-thuong-gap'
import { Route as ChinhSachBaoHanhRouteImport } from './routes/chinh-sach-bao-hanh'
import { Route as ChinhSachBaoMatRouteImport } from './routes/chinh-sach-bao-mat'
import { Route as ChinhSachDichVuRouteImport } from './routes/chinh-sach-dich-vu'
import { Route as DichVuRouteImport } from './routes/dich-vu'
import { Route as DieuKhoanSuDungRouteImport } from './routes/dieu-khoan-su-dung'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as KhuVucRouteImport } from './routes/khu-vuc'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SuaMayGiatRouteImport } from './routes/sua-may-giat'
import { Route as SuaMayLanhRouteImport } from './routes/sua-may-lanh'
import { Route as SuaMayNuocNongRouteImport } from './routes/sua-may-nuoc-nong'
import { Route as SuaTuLanhRouteImport } from './routes/sua-tu-lanh'
import { Route as VeSinhMayLanhRouteImport } from './routes/ve-sinh-may-lanh'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BangGiaRoute = BangGiaRouteImport.update({
  id: '/bang-gia',
  path: '/bang-gia',
  getParentRoute: () => rootRouteImport,
} as any)
const BaoTriDienLanhRoute = BaoTriDienLanhRouteImport.update({
  id: '/bao-tri-dien-lanh',
  path: '/bao-tri-dien-lanh',
  getParentRoute: () => rootRouteImport,
} as any)
const CauHoiThuongGapRoute = CauHoiThuongGapRouteImport.update({
  id: '/cau-hoi-thuong-gap',
  path: '/cau-hoi-thuong-gap',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinhSachBaoHanhRoute = ChinhSachBaoHanhRouteImport.update({
  id: '/chinh-sach-bao-hanh',
  path: '/chinh-sach-bao-hanh',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinhSachBaoMatRoute = ChinhSachBaoMatRouteImport.update({
  id: '/chinh-sach-bao-mat',
  path: '/chinh-sach-bao-mat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinhSachDichVuRoute = ChinhSachDichVuRouteImport.update({
  id: '/chinh-sach-dich-vu',
  path: '/chinh-sach-dich-vu',
  getParentRoute: () => rootRouteImport,
} as any)
const DichVuRoute = DichVuRouteImport.update({
  id: '/dich-vu',
  path: '/dich-vu',
  getParentRoute: () => rootRouteImport,
} as any)
const DieuKhoanSuDungRoute = DieuKhoanSuDungRouteImport.update({
  id: '/dieu-khoan-su-dung',
  path: '/dieu-khoan-su-dung',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const KhuVucRoute = KhuVucRouteImport.update({
  id: '/khu-vuc',
  path: '/khu-vuc',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SuaMayGiatRoute = SuaMayGiatRouteImport.update({
  id: '/sua-may-giat',
  path: '/sua-may-giat',
  getParentRoute: () => rootRouteImport,
} as any)
const SuaMayLanhRoute = SuaMayLanhRouteImport.update({
  id: '/sua-may-lanh',
  path: '/sua-may-lanh',
  getParentRoute: () => rootRouteImport,
} as any)
const SuaMayNuocNongRoute = SuaMayNuocNongRouteImport.update({
  id: '/sua-may-nuoc-nong',
  path: '/sua-may-nuoc-nong',
  getParentRoute: () => rootRouteImport,
} as any)
const SuaTuLanhRoute = SuaTuLanhRouteImport.update({
  id: '/sua-tu-lanh',
  path: '/sua-tu-lanh',
  getParentRoute: () => rootRouteImport,
} as any)
const VeSinhMayLanhRoute = VeSinhMayLanhRouteImport.update({
  id: '/ve-sinh-may-lanh',
  path: '/ve-sinh-may-lanh',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bang-gia': typeof BangGiaRoute
  '/bao-tri-dien-lanh': typeof BaoTriDienLanhRoute
  '/cau-hoi-thuong-gap': typeof CauHoiThuongGapRoute
  '/chinh-sach-bao-hanh': typeof ChinhSachBaoHanhRoute
  '/chinh-sach-bao-mat': typeof ChinhSachBaoMatRoute
  '/chinh-sach-dich-vu': typeof ChinhSachDichVuRoute
  '/dich-vu': typeof DichVuRoute
  '/dieu-khoan-su-dung': typeof DieuKhoanSuDungRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/khu-vuc': typeof KhuVucRoute
  '/lien-he': typeof LienHeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sua-may-giat': typeof SuaMayGiatRoute
  '/sua-may-lanh': typeof SuaMayLanhRoute
  '/sua-may-nuoc-nong': typeof SuaMayNuocNongRoute
  '/sua-tu-lanh': typeof SuaTuLanhRoute
  '/ve-sinh-may-lanh': typeof VeSinhMayLanhRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bang-gia': typeof BangGiaRoute
  '/bao-tri-dien-lanh': typeof BaoTriDienLanhRoute
  '/cau-hoi-thuong-gap': typeof CauHoiThuongGapRoute
  '/chinh-sach-bao-hanh': typeof ChinhSachBaoHanhRoute
  '/chinh-sach-bao-mat': typeof ChinhSachBaoMatRoute
  '/chinh-sach-dich-vu': typeof ChinhSachDichVuRoute
  '/dich-vu': typeof DichVuRoute
  '/dieu-khoan-su-dung': typeof DieuKhoanSuDungRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/khu-vuc': typeof KhuVucRoute
  '/lien-he': typeof LienHeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sua-may-giat': typeof SuaMayGiatRoute
  '/sua-may-lanh': typeof SuaMayLanhRoute
  '/sua-may-nuoc-nong': typeof SuaMayNuocNongRoute
  '/sua-tu-lanh': typeof SuaTuLanhRoute
  '/ve-sinh-may-lanh': typeof VeSinhMayLanhRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bang-gia': typeof BangGiaRoute
  '/bao-tri-dien-lanh': typeof BaoTriDienLanhRoute
  '/cau-hoi-thuong-gap': typeof CauHoiThuongGapRoute
  '/chinh-sach-bao-hanh': typeof ChinhSachBaoHanhRoute
  '/chinh-sach-bao-mat': typeof ChinhSachBaoMatRoute
  '/chinh-sach-dich-vu': typeof ChinhSachDichVuRoute
  '/dich-vu': typeof DichVuRoute
  '/dieu-khoan-su-dung': typeof DieuKhoanSuDungRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/khu-vuc': typeof KhuVucRoute
  '/lien-he': typeof LienHeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sua-may-giat': typeof SuaMayGiatRoute
  '/sua-may-lanh': typeof SuaMayLanhRoute
  '/sua-may-nuoc-nong': typeof SuaMayNuocNongRoute
  '/sua-tu-lanh': typeof SuaTuLanhRoute
  '/ve-sinh-may-lanh': typeof VeSinhMayLanhRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bang-gia'
    | '/bao-tri-dien-lanh'
    | '/cau-hoi-thuong-gap'
    | '/chinh-sach-bao-hanh'
    | '/chinh-sach-bao-mat'
    | '/chinh-sach-dich-vu'
    | '/dich-vu'
    | '/dieu-khoan-su-dung'
    | '/gioi-thieu'
    | '/khu-vuc'
    | '/lien-he'
    | '/sitemap.xml'
    | '/sua-may-giat'
    | '/sua-may-lanh'
    | '/sua-may-nuoc-nong'
    | '/sua-tu-lanh'
    | '/ve-sinh-may-lanh'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bang-gia'
    | '/bao-tri-dien-lanh'
    | '/cau-hoi-thuong-gap'
    | '/chinh-sach-bao-hanh'
    | '/chinh-sach-bao-mat'
    | '/chinh-sach-dich-vu'
    | '/dich-vu'
    | '/dieu-khoan-su-dung'
    | '/gioi-thieu'
    | '/khu-vuc'
    | '/lien-he'
    | '/sitemap.xml'
    | '/sua-may-giat'
    | '/sua-may-lanh'
    | '/sua-may-nuoc-nong'
    | '/sua-tu-lanh'
    | '/ve-sinh-may-lanh'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/bang-gia'
    | '/bao-tri-dien-lanh'
    | '/cau-hoi-thuong-gap'
    | '/chinh-sach-bao-hanh'
    | '/chinh-sach-bao-mat'
    | '/chinh-sach-dich-vu'
    | '/dich-vu'
    | '/dieu-khoan-su-dung'
    | '/gioi-thieu'
    | '/khu-vuc'
    | '/lien-he'
    | '/sitemap.xml'
    | '/sua-may-giat'
    | '/sua-may-lanh'
    | '/sua-may-nuoc-nong'
    | '/sua-tu-lanh'
    | '/ve-sinh-may-lanh'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BangGiaRoute: typeof BangGiaRoute
  BaoTriDienLanhRoute: typeof BaoTriDienLanhRoute
  CauHoiThuongGapRoute: typeof CauHoiThuongGapRoute
  ChinhSachBaoHanhRoute: typeof ChinhSachBaoHanhRoute
  ChinhSachBaoMatRoute: typeof ChinhSachBaoMatRoute
  ChinhSachDichVuRoute: typeof ChinhSachDichVuRoute
  DichVuRoute: typeof DichVuRoute
  DieuKhoanSuDungRoute: typeof DieuKhoanSuDungRoute
  GioiThieuRoute: typeof GioiThieuRoute
  KhuVucRoute: typeof KhuVucRoute
  LienHeRoute: typeof LienHeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuaMayGiatRoute: typeof SuaMayGiatRoute
  SuaMayLanhRoute: typeof SuaMayLanhRoute
  SuaMayNuocNongRoute: typeof SuaMayNuocNongRoute
  SuaTuLanhRoute: typeof SuaTuLanhRoute
  VeSinhMayLanhRoute: typeof VeSinhMayLanhRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bang-gia': {
      id: '/bang-gia'
      path: '/bang-gia'
      fullPath: '/bang-gia'
      preLoaderRoute: typeof BangGiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bao-tri-dien-lanh': {
      id: '/bao-tri-dien-lanh'
      path: '/bao-tri-dien-lanh'
      fullPath: '/bao-tri-dien-lanh'
      preLoaderRoute: typeof BaoTriDienLanhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cau-hoi-thuong-gap': {
      id: '/cau-hoi-thuong-gap'
      path: '/cau-hoi-thuong-gap'
      fullPath: '/cau-hoi-thuong-gap'
      preLoaderRoute: typeof CauHoiThuongGapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinh-sach-bao-hanh': {
      id: '/chinh-sach-bao-hanh'
      path: '/chinh-sach-bao-hanh'
      fullPath: '/chinh-sach-bao-hanh'
      preLoaderRoute: typeof ChinhSachBaoHanhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinh-sach-bao-mat': {
      id: '/chinh-sach-bao-mat'
      path: '/chinh-sach-bao-mat'
      fullPath: '/chinh-sach-bao-mat'
      preLoaderRoute: typeof ChinhSachBaoMatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinh-sach-dich-vu': {
      id: '/chinh-sach-dich-vu'
      path: '/chinh-sach-dich-vu'
      fullPath: '/chinh-sach-dich-vu'
      preLoaderRoute: typeof ChinhSachDichVuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dich-vu': {
      id: '/dich-vu'
      path: '/dich-vu'
      fullPath: '/dich-vu'
      preLoaderRoute: typeof DichVuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieu-khoan-su-dung': {
      id: '/dieu-khoan-su-dung'
      path: '/dieu-khoan-su-dung'
      fullPath: '/dieu-khoan-su-dung'
      preLoaderRoute: typeof DieuKhoanSuDungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khu-vuc': {
      id: '/khu-vuc'
      path: '/khu-vuc'
      fullPath: '/khu-vuc'
      preLoaderRoute: typeof KhuVucRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sua-may-giat': {
      id: '/sua-may-giat'
      path: '/sua-may-giat'
      fullPath: '/sua-may-giat'
      preLoaderRoute: typeof SuaMayGiatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sua-may-lanh': {
      id: '/sua-may-lanh'
      path: '/sua-may-lanh'
      fullPath: '/sua-may-lanh'
      preLoaderRoute: typeof SuaMayLanhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sua-may-nuoc-nong': {
      id: '/sua-may-nuoc-nong'
      path: '/sua-may-nuoc-nong'
      fullPath: '/sua-may-nuoc-nong'
      preLoaderRoute: typeof SuaMayNuocNongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sua-tu-lanh': {
      id: '/sua-tu-lanh'
      path: '/sua-tu-lanh'
      fullPath: '/sua-tu-lanh'
      preLoaderRoute: typeof SuaTuLanhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ve-sinh-may-lanh': {
      id: '/ve-sinh-may-lanh'
      path: '/ve-sinh-may-lanh'
      fullPath: '/ve-sinh-may-lanh'
      preLoaderRoute: typeof VeSinhMayLanhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BangGiaRoute: BangGiaRoute,
  BaoTriDienLanhRoute: BaoTriDienLanhRoute,
  CauHoiThuongGapRoute: CauHoiThuongGapRoute,
  ChinhSachBaoHanhRoute: ChinhSachBaoHanhRoute,
  ChinhSachBaoMatRoute: ChinhSachBaoMatRoute,
  ChinhSachDichVuRoute: ChinhSachDichVuRoute,
  DichVuRoute: DichVuRoute,
  DieuKhoanSuDungRoute: DieuKhoanSuDungRoute,
  GioiThieuRoute: GioiThieuRoute,
  KhuVucRoute: KhuVucRoute,
  LienHeRoute: LienHeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuaMayGiatRoute: SuaMayGiatRoute,
  SuaMayLanhRoute: SuaMayLanhRoute,
  SuaMayNuocNongRoute: SuaMayNuocNongRoute,
  SuaTuLanhRoute: SuaTuLanhRoute,
  VeSinhMayLanhRoute: VeSinhMayLanhRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
